### ISSUE TITLE
Klai 2019 error

### ISSUE THREAD

**Issue by covid20-hub** [tothi/rbcd-attack#3] opened 2020-05-05 18:27 UTC
I keep getting this error in kali 2019

```
ProxyChains-3.1 (http://proxychains.sf.net)
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using htb.local\test-svc account with password ***
|S-chain|-<>-127.0.0.1:1080-<><>-192.168.3.203:389-<><>-OK
[*] LDAP bind OK
[*] Initializing domainDumper()
Traceback (most recent call last):
  File "rbcd.py", line 38, in <module>
    cnf = ldapdomaindump.domainDumpConfig()
AttributeError: module 'ldapdomaindump' has no attribute 'domainDumpConfig'
```

**Comment by covid20-hub** [comment] 2020-05-05 18:37
Anyone tried this for HADES on any kali 2020 or kali 2019 and worked?

**Comment by tothi** [comment] 2020-05-05 20:15
it worked with a recent, proper Impacket install.

**Comment by covid20-hub** [comment] 2020-05-05 21:06
please tell us how? pip3 install . beacsue pip install does not work

**Comment by tothi** [comment] 2020-05-06 17:28
fyi: pushed an update with options in the script and clearer example. note, that the identity format for `rbcd.py` must be domain\user:pass where domain is the _NetBIOS_ domain name.

**Comment by tothi** [comment] 2020-05-06 17:30
Duplicate of #2

**Closed as completed by tothi** 2020-05-06 17:30 UTC
